baseURL: https://nbcp.xyz
title: Noah Piper
languageCode: en-us
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: no
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: Noah B.C. Piper
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  customCSS: ["css/custom.css"]
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04
  dateformShort: Jan 2
  description: Noah Piper's Homepage
  disableReadOtherPosts: no
  enableGlobalLanguageMenu: yes
  enableSharingButtons: no
  enableThemeToggle: no
  favicon:
    url: ../../icon-192x192.png
  footer:
    author: yes
    copyright: no
    rss: yes
    topText: []
    trademark: yes
  homeSubtitle: Receptor Biologist, Pharmacologist
  images: ''
  justifyContent: no
  keywords: ''
  logo:
    logoHomeLink: /
    logoMark: 'ğŸ¤ '
    logoMark2: 'ğŸ‘¨â€ğŸ”¬'
    logoText: "%>% as.matrix()"
    #logoText2: ""
  social:
    - name: twitter
      url: https://twitter.com/noahbcp
    - name: email
      url: mailto:noah@nbcp.xyz
    - name: github
      url: https://github.com/noahbcp
    - name: linkedin
      url: https://linkedin.com/in/noah-piper-22572b62/
    - name: orcid
      url: https://orcid.org/0000-0003-3711-301X
languages:
  en:
    weight: 1
  cn:
    title: æ½˜è¯ºäºš
    homesubtitle: åˆ†å­ç”Ÿç‰©å­¦å®¶
    menu:
      main:
      - identifier: about
        name: å…³äº
        url: about/
      - identifier: blog
        name: åšå®¢
        url: ../post/
      - identifier: cv
        name: ç®€å†
        url: ../cv/
      - identifier: publications
        name: å‡ºç‰ˆç‰©
        url: ../publications/
    weight: 2
menu:
  main:
    - identifier: about
      name: about
      url: about/
    - identifier: cv
      name: cv
      url: cv/
    - identifier: blog
      name: blog
      url: post
    - identifier: publications
      name: publications
      url: publications
